########################################################
#                        Practice                      #
########################################################

General:
  prefix: '&7[&ePractice&7]'
  start_player_elo: 1000

# Configuration of database (MySQL)
Database:
  enabled: false
  user: user
  pass: pass
  url: url
  port: 3006
  database: database

# Locations
Spawn:
  world: {}
  x: {}
  y: {}
  z: {}


# Arena Configuration
# /!\ Put a default arenas number wich proportional to the performances of your server !
Arena:
  number_default_arena: 10

########################################################
#                        Practice                      #
########################################################