name: Practice
author: SmakYop
version: 1.0-SNAPSHOT
main: com.spigot.practice.Practice
depend: [WorldEdit]
commands:
     setspawn:
        description: Command for set the spawn location
     arena:
     party:
       description: Command to manage your party
     match: